# Name: Sagar Shah
# Advanced Data Science Assignment - 1
# Email-id: shahsagar233@gmail.com

# 1. Eigenvalues and Eigenvectors of an array

In [4]:
# Function: To find the Eigenvalues and Eigenvectors of a square matrix
# Syntax: eigenvalues, eigenvectors = numpy.linalg.eig()
# Code:
import numpy as np
a = np.random.randint(0,9,(4,4))
ev,evec = np.linalg.eig(a)
print(a)
print("Printing the Eigen values of the array:\n",ev)
print("Printing the Eigen vectors of the array:\n",evec)

[[4 1 7 7]
 [4 3 0 2]
 [8 6 2 6]
 [6 0 5 1]]
Printing the Eigen values of the array:
 [16.49820238 -4.21027505 -2.         -0.28792734]
Printing the Eigen vectors of the array:
 [[-0.60862456 -0.60220205 -0.34188173  0.34723657]
 [-0.24476373  0.11657982  0.45584231 -0.66772173]
 [-0.61702099 -0.09445144  0.68376346 -0.5205519 ]
 [-0.43468605  0.78411782 -0.45584231  0.40323713]]


# 2. Digitize()

In [15]:
# Function: Return the indices of the bins to which each value in input array belongs.
    #=========  =============  ============================
    #`right`    order of bins  returned index `i` satisfies
    #=========  =============  ============================
    #``False``  increasing     ``bins[i-1] <= x < bins[i]``
    #``True``   increasing     ``bins[i-1] < x <= bins[i]``
    #``False``  decreasing     ``bins[i-1] > x >= bins[i]``
    #``True``   decreasing     ``bins[i-1] >= x > bins[i]``
    #=========  =============  ============================
    #If values in `x` are beyond the bounds of `bins`, 0 or ``len(bins)`` is returned as appropriate.
    # bin should be in increasing order.
# Syntax: np.digitize(Array, Bin, Right=False)
# Code:
a = np.random.randint(0,9,5)
b = sorted(np.random.randint(0,9,7))
print("Printing the array:\n",a)
print("Printing the bin values array:\n",b)
c = np.digitize(a, b, right=False)
print("Printing the array holding the indices of all the values of bins:\n",c)

Printing the array:
 [5 0 7 3 1]
Printing the bin values array:
 [0, 2, 2, 5, 6, 6, 8]
Printing the array holding the indices of all the values of bins:
 [4 1 6 3 1]


# 3. Repeat()

In [24]:
# Function: Repeats elements of the array
    # repetitions = No. of repetitions of each array elements along the given axis
    # axis= Axis along which we want to repeat values. By default, it returns a flat output array.
# Syntax: numpy.repeat(arr, repetitions, axis = None)
# Code:
a = np.random.randint(0,9,(3,3))
print(a)
a_d = np.repeat(a, 2)
print("Printing the array with repetation of 2 times and default setting for axis:\n",a_d)
a_0 = np.repeat(a, 2, axis = 0)
print("Printing the array with repetation of 2 times and axis = 0 (Row Wise):\n",a_0)
a_1 = np.repeat(a, 2, axis = 1)
print("Printing the array with repetation of 2 times and axis = 1 (Column Wise):\n",a_1)

[[1 8 4]
 [6 3 0]
 [0 7 3]]
Printing the array with repetation of 2 times and default setting for axis:
 [1 1 8 8 4 4 6 6 3 3 0 0 0 0 7 7 3 3]
Printing the array with repetation of 2 times and axis = 0 (Row Wise):
 [[1 8 4]
 [1 8 4]
 [6 3 0]
 [6 3 0]
 [0 7 3]
 [0 7 3]]
Printing the array with repetation of 2 times and axis = 1 (Column Wise):
 [[1 1 8 8 4 4]
 [6 6 3 3 0 0]
 [0 0 7 7 3 3]]


# 4. Squeeze()

In [38]:
# Function: When we want to remove single-dimensional entries from the shape of an array.
    # axis= Selects a subset of the single-dimensional entries in the shape. 
    #       If an axis is selected with shape entry greater than one, an error is raised.
# Syntax: numpy.squeeze(arr, axis=None)
# Code:
a = np.random.randint(0,9,(1,4,5))
print ("Input array : \n", a)  
print("Shape of input array : \n", a.shape)   
b = np.squeeze(a, axis = 0)
print("Output squeezed array : \n", b) 
print("Shape of output squeezed array : \n", b.shape)  

Input array : 
 [[[1 2 3 6 8]
  [0 4 3 3 2]
  [7 2 4 1 7]
  [2 1 5 8 8]]]
Shape of input array : 
 (1, 4, 5)
Output squeezed array : 
 [[1 2 3 6 8]
 [0 4 3 3 2]
 [7 2 4 1 7]
 [2 1 5 8 8]]
Shape of output squeezed array : 
 (4, 5)


# 5. Linspace()

In [3]:
# Function: Returns number spaced evenly with respect to interval
# Syntax: numpy.linspace(start,stop,num = 50(it is a default value),endpoint = True,retstep = False, dtype = None)
# Code:
import numpy as np
a = np.linspace(2.0, 3.0, 10, endpoint=False,retstep = True)
print ("Printing the array with endpoint = false \n", a)
b = np.linspace(2.0, 3.0, 10, endpoint=True,retstep = True)
print ("Printing the array with endpoint = true \n", b)

Printing the array with endpoint = false 
 (array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]), 0.1)
Printing the array with endpoint = true 
 (array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ]), 0.1111111111111111)


# 6. Clip()

In [5]:
# Function: Used to Limit the values in an array
# Syntax: numpy.clip(a, a_min, a_max, out=None)
# Code:
a = np.arange(10)
print ("Printing the array \n", a)
b = np.clip(a, 3, 6)
print ("Printing the clipped array with a sigle value for clipping \n", b)
c = np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)
print ("Printing the clipped array with a list for clipping \n", c)

Printing the array 
 [0 1 2 3 4 5 6 7 8 9]
Printing the clipped array with a sigle value for clipping 
 [3 3 3 3 4 5 6 6 6 6]
Printing the clipped array with a list for clipping 
 [3 4 2 3 4 5 6 7 8 8]


# 7. Extract()

In [6]:
# Function: Returns elements of input array if they satisfy some specified condition
# Syntax: numpy.extract(condition, array)
# Code: 
a = np.random.randint(0,9,(3,3))
print(a)
condition = np.mod(a, 2)==0
print("Array Condition: \n", condition) 
b = np.extract(condition, a)
print("Elements that satisfy condition: \n", b)

[[3 0 8]
 [0 0 7]
 [4 3 1]]
Array Condition: 
 [[False  True  True]
 [ True  True False]
 [ True False False]]
Elements that satisfy condition: 
 [0 8 0 0 4]


# 8. Argpartition()

In [64]:
# Function: Used to create a indirect partitioned copy of input array with its elements rearranged in such a way 
           #that the value of the element in k-th position is in the position it would be in a sorted array. 
           #All elements smaller than the k-th element are moved before this element and 
           #all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.
           #It returns an array of indices of the same shape as input array
# Syntax: numpy.argpartition(arr, kth, axis=-1, kind=’introselect’, order=None)
# Code:
a = np.random.randint(0,9,5)
b = np.argpartition(a,3) 
print ("Printing the array \n", a)
print ("Printing the partitioned array indexes \n", b)
print ("Printing the partitioned array \n",a[b])

Printing the array 
 [5 1 4 8 3]
Printing the partitioned array indexes 
 [1 4 2 0 3]
Printing the partitioned array 
 [1 3 4 5 8]


# 9. Setdiff1d()

In [7]:
# Function: Find the set difference of two arrays. Return the unique values in ar1 that are not in ar2.
            #assume_unique --> If True, the input arrays are both assumed to be unique, which can speed up the calculation. 
                               #Default is False.
# Syntax: numpy.setdiff1d(arr1, arr2, assume_unique = False)
# Code:
import numpy as np
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
b = np.random.randint(0,9,(3,3)) 
print ("Printing the array b \n", b)
d_a_b = np.setdiff1d(a, b) 
print ("Printing the array of unique values in a\n", d_a_b) 

Printing the array a 
 [[6 4 4]
 [2 1 3]
 [1 4 0]]
Printing the array b 
 [[2 8 1]
 [4 8 0]
 [5 4 2]]
Printing the array of unique values in a
 [3 6]


# 10. Itemsize

In [15]:
# Function: Return the length of one array element in bytes
# Syntax: numpy.ndarray.itemsize(arr)
# Code:
a = np.array(np.random.randint(0,9,(3,3)), dtype=np.float64)
print ("Printing the array a \n", a)
print ("Length of one array element in bytes of array a is \n", a.itemsize)
b = np.array(np.random.randint(0,9,(3,3)), dtype=np.complex128)
print ("Printing the array b \n", b)
print ("Length of one array element in bytes of array b is \n", b.itemsize)

Printing the array a 
 [[0. 6. 6.]
 [8. 1. 2.]
 [8. 3. 6.]]
Length of one array element in bytes of array a is 
 8
Printing the array b 
 [[6.+0.j 6.+0.j 3.+0.j]
 [6.+0.j 6.+0.j 2.+0.j]
 [5.+0.j 0.+0.j 8.+0.j]]
Length of one array element in bytes of array b is 
 16


# 11. Hstack()

In [16]:
# Function: Stack arrays in sequence horizontally (column wise)
# Syntax: numpy.hstack(tup)
# Code:
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
b = np.random.randint(0,9,(3,3))
print ("Printing the array b \n", b)
c = np.hstack((a,b))
print ("Printing the hstacked array \n", c)

Printing the array a 
 [[8 5 4]
 [8 3 2]
 [1 5 6]]
Printing the array b 
 [[7 7 8]
 [4 0 2]
 [5 3 5]]
Printing the hstacked array 
 [[8 5 4 7 7 8]
 [8 3 2 4 0 2]
 [1 5 6 5 3 5]]


# 12. Vstack()

In [18]:
# Function: Stack arrays in sequence verically (row wise)
# Syntax: numpy.vstack(tup)
# Code:
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
b = np.random.randint(0,9,(3,3))
print ("Printing the array b \n", b)
c = np.vstack((a,b))
print ("Printing the vstacked array \n", c)

Printing the array a 
 [[6 7 7]
 [2 2 6]
 [0 4 6]]
Printing the array b 
 [[1 7 5]
 [3 8 6]
 [7 2 3]]
Printing the vstacked array 
 [[6 7 7]
 [2 2 6]
 [0 4 6]
 [1 7 5]
 [3 8 6]
 [7 2 3]]


# 13. Hsplit()

In [23]:
# Function: function split an array into multiple sub-arrays horizontally (column-wise) equally. 
            #hsplit is equivalent to split with axis=1, 
            #the array is always split along the second axis regardless of the array dimension.
# Syntax: numpy.hsplit(arr, indices_or_sections)
# Code:
a = np.random.randint(0,9,(4,4))
print ("Printing the array a \n", a)
b = np.hsplit(a, 2)
print ("Printing the hsplited array \n", b)

Printing the array a 
 [[6 4 8 0]
 [1 4 3 2]
 [0 1 0 1]
 [0 2 4 8]]
Printing the hsplited array 
 [array([[6, 4],
       [1, 4],
       [0, 1],
       [0, 2]]), array([[8, 0],
       [3, 2],
       [0, 1],
       [4, 8]])]


# 14. Vsplit()

In [24]:
# Function: function split an array into multiple sub-arrays horizontally (column-wise) equally. 
            #hsplit is equivalent to split with axis=0, 
            #the array is always split along the first axis regardless of the array dimension.
# Syntax: numpy.vsplit(arr, indices_or_sections)
# Code:
a = np.random.randint(0,9,(4,4))
print ("Printing the array a \n", a)
b = np.vsplit(a, 2)
print ("Printing the vsplited array \n", b)

Printing the array a 
 [[7 1 5 4]
 [5 5 1 5]
 [3 8 5 6]
 [6 5 4 3]]
Printing the vsplited array 
 [array([[7, 1, 5, 4],
       [5, 5, 1, 5]]), array([[3, 8, 5, 6],
       [6, 5, 4, 3]])]


# 15. View vs Shallow Copy

In [26]:
# Function: The view is just a view of the original array and view does not own the data. 
            #When we make changes to the view it affects the original array, 
            #and when changes are made to the original array it affects the view
            #Both have different ids
# Syntax: arr.view()
# Code:
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
print("id of a \n", id(a))
b = a.view()
print ("Printing the viwed array b \n", b)
print("id of b \n", id(b))
a[0,0] = 12
print("Printing the new array a \n", a) 
print("Printing the new viewed array b \n", b) 

Printing the array a 
 [[0 6 7]
 [5 3 8]
 [1 6 1]]
id of a 
 62139872
Printing the viwed array b 
 [[0 6 7]
 [5 3 8]
 [1 6 1]]
id of b 
 62107800
Printing the new array a 
 [[12  6  7]
 [ 5  3  8]
 [ 1  6  1]]
Printing the new viewed array b 
 [[12  6  7]
 [ 5  3  8]
 [ 1  6  1]]


# 16. Deep Copy

In [27]:
# Function: The copy is completely a new array and copy owns the data. 
            #When we make changes to the copy it does not affect the original array, 
            #and when changes are made to the original array it does not affect the copy.
            #Both have different ids
# Syntax: arr.copy()
# Code:
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
print("id of a \n", id(a))
b = a.copy()
print ("Printing the copied array b \n", b)
print("id of b \n", id(b))
a[0,0] = 12
print("Printing the new array a \n", a) 
print("Printing the original copied array b \n", b) 

Printing the array a 
 [[4 8 5]
 [4 3 0]
 [0 6 1]]
id of a 
 61817264
Printing the copied array b 
 [[4 8 5]
 [4 3 0]
 [0 6 1]]
id of b 
 62107960
Printing the new array a 
 [[12  8  5]
 [ 4  3  0]
 [ 0  6  1]]
Printing the original copied array b 
 [[4 8 5]
 [4 3 0]
 [0 6 1]]


# 17. Copy() and Deepcopy()

In [33]:
#COPY()
# Function: Function is a shallow copy and will not copy object elements within arrays. 
            #This is mainly important for arrays containing Python objects. 
            #The new array will contain the same object which may lead to surprises if that object can be modified.
# Syntax: numpy.copy()
# Code:
import numpy as np
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
print ("Printing the array a \n", a)
b = np.copy(a)
print ("Printing the shallowed array b \n", b)
# Object element within array is mutable i.e. change will reflect in both arrays
b[2][0] = 10
print ("Printing the new array a \n", a)
print ("Printing the new shallowed array b \n", b)
# Principle Object element is immutable i.e. change will reflect in copied array only
b[0] = 10
print ("Printing the new array a \n", a)
print ("Printing the new shallowed array b \n", b)

#DEEPCOPY()
#Function: To ensure all elements within an object array are copied
#Syntax: copy.deepcopy
#Code:
import copy
c = np.array([5, 'k', [4, 8, 9]], dtype=object)
print ("Printing the array a \n", c)
d = copy.deepcopy(c)
print ("Printing the shallowed array b \n", d)
#All the object element within array are immutable i.e. change will reflect in copied array only
d[2][0] = 10
d[0] = 10
print ("Printing the new array a \n", c)
print ("Printing the new deepcopied array b \n", d)

Printing the array a 
 [1 'm' list([2, 3, 4])]
Printing the shallowed array b 
 [1 'm' list([2, 3, 4])]
Printing the new array a 
 [1 'm' list([10, 3, 4])]
Printing the new shallowed array b 
 [1 'm' list([10, 3, 4])]
Printing the new array a 
 [1 'm' list([10, 3, 4])]
Printing the new shallowed array b 
 [10 'm' list([10, 3, 4])]
Printing the array a 
 [5 'k' list([4, 8, 9])]
Printing the shallowed array b 
 [5 'k' list([4, 8, 9])]
Printing the new array a 
 [5 'k' list([4, 8, 9])]
Printing the new deepcopied array b 
 [10 'k' list([10, 8, 9])]


# 18. Meshgrid()

In [63]:
# Function: Return coordinate matrices from coordinate vectors.
# Syntax: numpy.vsplit(arr, indices_or_sections)
# Code:
x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 4)
xa, ya = np.meshgrid(x, y)
print('Printing X-axis coordinates \n', xa)
print('Printing Y-axis coordinates \n',ya)
x_y = np.array([xa,ya]).T.reshape(-1, 2)
print('Printing matrix of coordinates \n', x_y)

Printing X-axis coordinates 
 [[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
Printing Y-axis coordinates 
 [[-1.         -1.         -1.         -1.         -1.        ]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 1.          1.          1.          1.          1.        ]]
Printing matrix of coordinates 
 [[-1.         -1.        ]
 [-1.         -0.33333333]
 [-1.          0.33333333]
 [-1.          1.        ]
 [-0.5        -1.        ]
 [-0.5        -0.33333333]
 [-0.5         0.33333333]
 [-0.5         1.        ]
 [ 0.         -1.        ]
 [ 0.         -0.33333333]
 [ 0.          0.33333333]
 [ 0.          1.        ]
 [ 0.5        -1.        ]
 [ 0.5        -0.33333333]
 [ 0.5         0.33333333]
 [ 0.5         1.        ]
 [ 1.         -1.        ]
 [ 1.         -0.33333333]
 [ 1.          0.33333333]
 [ 1.          1.        ]]


# 19. Swapaxes()

In [75]:
# Function: Function interchange two axes of an array
# Syntax: numpy.swapaxes(arr, axis1, axis2)
# Code:
a = np.random.randint(0,9,(3,3))
b = np.swapaxes(a, 0, 1) 
print ('Printing array a \n', a) 
print ('Printing array b \n', b)

Printing array a 
 [[2 6 7]
 [6 0 3]
 [7 6 5]]
Printing array b 
 [[2 6 7]
 [6 0 6]
 [7 3 5]]


# 20. Column_stack()

In [77]:
# Function: function is used to stack 1-D arrays as columns into a 2-D array.
            #It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array.
# Syntax: numpy.column_stack()
# Code:
a = np.random.randint(0,9,(3,3))
print ("Printing the array a \n", a)
b = np.random.randint(0,9,(3,3))
print ("Printing the array b \n", b)
c = np.column_stack((a,b))
print ("Printing the column stacked array \n", c)

Printing the array a 
 [[8 6 5]
 [3 4 0]
 [0 0 4]]
Printing the array b 
 [[4 8 1]
 [3 8 3]
 [4 6 3]]
Printing the column stacked array 
 [[8 6 5 4 8 1]
 [3 4 0 3 8 3]
 [0 0 4 4 6 3]]
